### ISSUE TITLE
Error with dataset url

### ISSUE THREAD

**Issue by mengchengyao** [epang-ucas/Evaluate_LLMs_to_Genes#1]
Thank you for your great work.
When I download the datasets with your url, an error occurred as follows:

![图片](https://github.com/epang-ucas/Evaluate_LLMs_to_Genes/assets/46958122/61031dc6-5acb-40aa-aebc-273bc7531855)

Could you update the url of datasets?

Bests

**Comment by epang-ucas** [comment]
Thank you for your attention to our work and for helping identify the issues. The data address has now been corrected. If you have any further questions, please feel free to leave a message.

**Comment by mengchengyao** [comment]
Many thanks
